services:
  server:
    restart: unless-stopped
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - client

  client:
    restart: unless-stopped
    build:
      context: ./frontend
    ports:
      - 80:80